FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y nano vim

COPY . /app/

EXPOSE 8000

RUN rm -rf users/migrations
RUN python manage.py makemigrations

# Run the Django development server
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD python manage.py migrate && python manage.py runserver 0.0.0.0:8000